version: "3.5"

networks:
 kong:
  driver: bridge
  name: kong

volumes:
  portainer_data:

services:

  #######################################
  # Portainer
  #######################################
  portainer:
    image: portainer/portainer
    restart: always
    networks:
      - kong
    expose:
       - 9000
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data
