version: "3.5"

networks:
 kong:
  driver: bridge
  name: kong-net
 kong-net-config:

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6-alpine
    restart: always
    networks:
      - kong-net-config
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    expose:
       - 5432
    volumes:
       - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-net-config
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong
      - kong-net-config
    environment:
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8002 ssl
      KONG_SSL_CERT: /etc/ssl/cert.pem
      KONG_SSL_CERT_KEY: /etc/ssl/key.pem
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "80:8000"
      - "443:8443"
    expose:
      - 8001
      - 8002
    volumes:
      - ./ssl:/etc/ssl

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/konga_db"
    networks:
      - kong-net-config
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
        - kong-net-config
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: ''
      TOKEN_SECRET: randomstringseccret
      DB_DATABASE: konga_db
      NODE_ENV: production
      SSL_KEY_PATH: /etc/ssl/key.pem
      SSL_CRT_PATH: /etc/ssl/cert.pem
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
    volumes:
      - ./ssl:/etc/ssl
